config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'links/new_index', to: 'links#new_index'
  get "links/ask" => "links#ask"
  get 'comments/threads' => 'comments#threads'
  get 'comments/voted_comments' => 'comments#voted_comments'
  get 'links/my_links' => 'links#my_links'
  get 'links/voted_links' => 'links#voted_links'

  resources :sessions, only: [:create, :destroy]

  resources :comments do
    member do
      put "like",    to: "comments#upvote"
      put "dislike", to: "comments#downvote"
      post "reply", to: "comments#doReply"
    end
    resources :comments
  end

  resources :links do
    member do
      put "like",    to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  resources :users
  root to: "links#index"

  namespace 'api' do

    #LINKS
    root "links#index"
    get "/submissions" => "links#index"
    get "/ask" => "links#ask"
    get "/newest" => "links#new_index"
    get "/submissions/:id" => "links#show"
    post "/submissions" => "links#submit"
    delete "/submissions/:id" => "links#delete"

    #COMMENTS
    get "/threads" => "comments#threads"
    delete "/comments/:id" => "comments#delete"
    get "/comments/:id" => "comments#show"
    post "/comments" => "comments#new"

    # USERS
    get "/users/:id" => "users#profile"
    put "/users/:id" => "users#update_user"
    post "/vote_submission" => "users#vote_submission"
    post "/vote_comment" => "users#vote_comment"

  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :link
  acts_as_votable
  belongs_to :commentable, polymorphic: true, optional:true
  has_many :comments, as: :commentable
end

app/controllers/api/comments_controller.rb
module Api
    class Api::CommentsController < Api::ApplicationController
        #skip_before_action :verify_authenticity_token

        def show
    		id = params[:id].to_i
            @comment = Comment.find_by(id: id)
            if @comment == nil
                render json: {status: "Comment not found"}, status: 404
            else
                render json: {status: 'SUCCESS', message:'Loaded specific comment', data: @comment}, status: 200
            end
        end

        def threads
            #api_token = request.headers["Authorization"]
            #user = User.find_by(api_key: api_token)
            userid = 1
            @comments = Comment.all.where(user_id: userid).order(created_at: :desc)
            @size = @comments.size
			if @size == 0
				render json: {status: 'SUCCESS', message: 'There are no comments'}, status: 200
			else
				render json: {status: 'SUCCESS', message: 'Loaded all comments', data: @comments}, status: 200
			end
        end

        def voted_comments
            id = params[:id].to_i
            user = User.find_by(id: id)
            @comments = Comment.all.select {|c| current_user.voted_for? c}
            @size = @comments.size
			if @size == 0
				render json: {status: 'SUCCESS', message: 'There are no comments'}, status: 200
			else
				render json: {status: 'SUCCESS', message: 'Loaded all voted comments', data: @comments}, status: 200
			end
        end

        def new
            #api_token = request.headers["Authorization"]
            content = params[:content]
			link_id = params[:submissionid]
			parent_id = params[:parentid]
			if !Link.exists?(id: link_id)
				render json: {error: "Link doesn't exist"}, status: 404 and return
			elsif !parent_id.nil? && parent_id != ""
				@commentPare = Comment.find_by(id: parent_id)
				if @commentPare.nil?
					render json: {error: "Comment to reply doesn't exist"}, status: 404 and return
				end
                #user = User.find_by(api_key: api_token)
                userid = 1
                c = @commentPare.comments.new(body: content, user_id: userid, link_id: link_id, cached_votes_up: nil)
                unless c.save
					render json: {error: "Internal server error"}, status: 500 and return
				end
			elsif content.nil? || content == ""
				render json: {error: "Empty content"}, status: 404 and return
			else
				user = User.find_by(api_key: api_token)
				c = Comment.new(body: content, user_id: userid, link_id: link_id, cached_votes_up: nil, commentable_id: parent_id)
				unless c.save
					render json: {error: "Internal server error"}, status: 500 and return
				end
			end
			render json: {status: "SUCCESS", id: c.id}, status: 201
        end
        
        def delete
            #api_token = request.headers["Authorization"]
            id = params[:id].to_i
            @comment = Comment.find_by(id: id)
            if @comment == nil
            	render json: {error: "Resource doesn't exist"}, status: 404 and return
            else 
                #id2 = User.find_by(api_key: api_token).id
                userid = 1
                if @comment.user_id != userid
                    render json: {error: "User not authorized to delete"}, status: 401 and return
                else
                    @comment.destroy
                    render json: {status: 'SUCCESS', message:'Comment deleted'}, status: 200 and return
                end
		    end
        end
        
    end      
end        

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  include SessionsHelper
  
  def new
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @comment = Comment.new
  end

  def edit
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    if @comment.user_id != current_user.id
      redirect_to "/links/"
    end
  end

  def threads
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @comments = Comment.all.where(user_id: current_user.id).order(created_at: :desc)
  end

  def voted_comments
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @comments = Comment.all.select {|c| current_user.voted_for? c}
end

  def create
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.link_id = @link.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @link, notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def doReply
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @comment = Comment.find(params[:comment_id])
    reply = @comment.comments.new(reply_params)
    reply.user_id = current_user.id
    reply.link_id = @comment.link_id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.link, notice: 'Reply was successfully created.' }
        format.json { render json: reply, status: :created, location: reply }
      else
        format.html { render action: "new" }
        format.json { render json: reply.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @comment = Comment.find(params[:id])
    @comment.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @comment = Comment.find(params[:id])
    @comment.unvote_by current_user
    redirect_back fallback_location: root_path
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment.link, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:link_id, :body, :user_id)
    end

    def reply_params
      params.require(:comment).permit(:id, :body, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for(comment) do %>
	<div class="comments_wrapper clearfix">
		<div class="pull-left">
			<p class="lead"><%= comment.body %></p>
			<p><small>Submitted <strong><%= time_ago_in_words(comment.created_at) %> ago</strong> 
			by <%= link_to comment.user.name, "/users/"+comment.user.id.to_s %></small></p>
		</div>
		<div class="btn-group pull-right">
		<% if comment.user == current_user -%>
			<%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-sm btn-default" %>
			<%= link_to 'Destroy', comment, method: :delete, data: { 
										confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
		<% else %>
			<%= link_to like_comment_path(comment), method: :put, class: "btn btn-default btn-sm" do %>
				<span class="glyphicon glyphicon-chevron-up"></span>
				Upvote
				<%= comment.get_upvotes.size %>
			<% end %>
			<%= link_to dislike_comment_path(comment), method: :put, class: "btn btn-default btn-sm" do %>
				<span class="glyphicon glyphicon-chevron-down">
				Unvote
			<% end %>
		<% end %>
		</div>
			<%= form_with model: Comment.new, url: reply_comment_path, local: true do |f| %>
				<div class="field">
				<%= f.text_area :body, class: "form-control" %>
				<%= hidden_field_tag "comment_id", "#{comment.id}" %>
				</div>
				<br>
				<%= f.submit "Add Reply", class: "btn btn-primary" %>
			<% end %>
		<ul>
			<div id="replies">
				<%= render :partial => comment.comments %>
			</div>
		</ul>
	</div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', @comment.link , class: "btn btn-default"%>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= link_to 'Show', comment , class: "btn btn-default"%></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) , class: "btn btn-default"%></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path , class: "btn btn-default"%>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path , class: "btn btn-default"%>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Link:</strong>
  <%= @comment.link_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) , class: "btn btn-default"%>

app/views/comments/threads.html.erb
<p id="notice"><%= notice %></p>

<h1>Threads</h1>

<table>
  <thead>
    <tr>
      <th>Link   </th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <div class="btn-group">
        <td><%= link_to 'Show', "/links/"+comment.link_id.to_s , class: "btn btn-default"%></td>
        <td><%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/comments/voted_comments.html.erb
<p id="notice"><%= notice %></p>

<h1>Voted comments</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.link_id %></td>
        <td><%= comment.body %></td>
        <div class="btn-group">
        <td><%= link_to 'Show', "/links/"+comment.link_id.to_s , class: "btn btn-default"%></td>
        <td><%= link_to 'Edit', edit_comment_path(comment), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>