config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'links/new_index', to: 'links#new_index'
  get "links/ask" => "links#ask"
  get 'comments/threads' => 'comments#threads'
  get 'comments/voted_comments' => 'comments#voted_comments'
  get 'links/my_links' => 'links#my_links'
  get 'links/voted_links' => 'links#voted_links'

  resources :sessions, only: [:create, :destroy]

  resources :comments do
    member do
      put "like",    to: "comments#upvote"
      put "dislike", to: "comments#downvote"
      post "reply", to: "comments#doReply"
    end
    resources :comments
  end

  resources :links do
    member do
      put "like",    to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  resources :users
  root to: "links#index"

  namespace 'api' do

    #LINKS
    root "links#index"
    get "/submissions" => "links#index"
    get "/ask" => "links#ask"
    get "/newest" => "links#new_index"
    get "/submissions/:id" => "links#show"
    post "/submissions" => "links#submit"
    delete "/submissions/:id" => "links#delete"

    #COMMENTS
    get "/threads" => "comments#threads"
    delete "/comments/:id" => "comments#delete"
    get "/comments/:id" => "comments#show"
    post "/comments" => "comments#new"

    # USERS
    get "/users/:id" => "users#profile"
    put "/users/:id" => "users#update_user"
    post "/vote_submission" => "users#vote_submission"
    post "/vote_comment" => "users#vote_comment"

  end

end

app/models/link.rb
class Link < ApplicationRecord
    acts_as_votable
    belongs_to :user
    has_many :comments, as: :commentable
    validates :title, presence:true
    validate :text_or_url_but_not_both
    validates :url, uniqueness: true, 
        format: { with: /\A#{URI::regexp(['http', 'https'])}\z/, message: "Ha de ser una URL vàlida"},
        if: :url?

    def text_or_url_but_not_both
        if url.blank? and text.blank?
            errors[:base] << "Specify the Url or the Text, but not both"
        elsif url? and text?
            errors[:base] << "Specify only the Url or the Text, but not both"
        end
    end
end

app/controllers/api/links_controller.rb
require 'uri'

module Api
	class Api::LinksController < Api::ApplicationController
        #skip_before_action :verify_authenticity_token

        def show
    		id = params[:id].to_i
            @link = Link.find_by(id: id)
            if @link == nil
                render json: {status: "Link not found"}, status: 404
            else
                @comment = Comment.where(link_id: id)
                @size = @comment.size
                if @size == 0
                    render json: {status: 'SUCCESS', message:'Loaded specific link', data: @link, comments: 'there are no comments'}, status: 200
				else
                    render json: {status: 'SUCCESS', message:'Loaded specific link', data: @link, comments: @comment}, status: 200
                end
            end
        end
		
		#GET /submissions
        def index
			@link = Link.all
			@size = @link.size
			if @size == 0
				render json: {status: 'SUCCESS', message: 'There are no submissions'}, status: 200
			else
				render json: {status: 'SUCCESS', message: 'Loaded all submissions', data: @link}, status: 200
			end
        end
        
        def ask
            @link = Link.all.where(url: '')
            @size = @link.size
			if @size == 0
				render json: {status: 'SUCCESS', message: 'There are no submissions'}, status: 200
			else
				render json: {status: 'SUCCESS', message: 'Loaded all submissions', data: @link}, status: 200
			end
        end

        def new_index
            @link = Link.all.order("created_at DESC")
            @size = @link.size
			if @size == 0
				render json: {status: 'SUCCESS', message: 'There are no submissions'}, status: 200
			else
				render json: {status: 'SUCCESS', message: 'Loaded all submissions', data: @link}, status: 200
			end
        end

        def delete
            #api_token = request.headers["Authorization"]
			id = params[:id].to_i
            @link = Link.find_by(id: id)
            if @link == nil
            	render json: {error: "Resource doesn't exist"}, status: 404 and return
            else 
				#id2 = User.find_by(api_key: api_token).id
				id2= 1
                if @link.user_id != id2
                    render json: {error: "User not authorized to delete"}, status: 401 and return
                else
                    Comment.where(link_id: id).destroy_all
                    @link.destroy
                    render json: {status: 'SUCCESS', message:'Link deleted'}, status: 200 and return
                end
		    end
		end

        def submit
            #api_token = request.headers["Authorization"]
            title = params[:title].to_s
            content = params[:body].to_s
            type = params[:type].to_s

            if type.nil? || type == ""
				render json: {error: "No link type specified"}, status: 400 and return
			elsif type != 'Url' and type != 'Ask'
				render json: {error: "Invalid link type"}, status: 400 and return
			elsif title.nil? || title == ""
				render json: {error: "No title specified"}, status: 400 and return
			elsif content.nil? || content == ""
				render json: {error: "Empty body"}, status: 400 and return
			elsif type == 'Url' and not valid_url?(content)
				render json: {error: "Invalid link"}, status: 400 and return
			elsif type == 'Url' and Link.exists?(:url => content)
				linkid = Link.where(url: content)[0].id
				linklink = "#{request.protocol}#{request.host_with_port}" + "/links/#{linkid}"
				render json: {error: "Link already exists", id: linkid, link: linklink}, status: 303 and return
            end
            
			#userid = User.find_by(api_key: api_token).id
			userid = 1
            if type == 'Url'
                c = Link.new(title: title, user_id: userid, url: content, text: nil)
            else
                c = Link.new(title: title, user_id: userid, url: nil, text: content)
            end

			unless c.save
				render json: {error: "Internal server error"}, status: 500 and return
			end

			link = "#{request.protocol}#{request.host_with_port}" + "/links/#{c.id}"
			render json: {status: "SUCCESS", id: c.id, link: link}, status: 201
        end


        private
			def valid_url?(uri)
				uri = URI.parse(uri)
				uri.is_a?(URI::HTTP) && !uri.host.nil?
			rescue URI::InvalidURIError
				false
			end
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  include SessionsHelper
  # GET /links
  # GET /links.json
  def index
    @links = Link.all.where.not(url: '').order(cached_votes_up: :desc)
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
  end

  # GET /links/new_index
  def new_index
    @links = Link.all.order("created_at DESC")
  end

  # GET /links/new
  def new
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @link = Link.new
  end

  # GET /links/ask
  def ask
    @links = Link.all.where(url: '')
  end
  
  def my_links
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @links = Link.all.where(user_id: current_user.id)
end

def voted_links
  unless is_logged_in?
    redirect_to "/auth/google_oauth2"
    return
  end
  @links = Link.all.select {|l| current_user.voted_for? l}
end

  # GET /links/1/edit
  def edit
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    if @link.user_id != current_user.id
      redirect_to "/links/"
    end
  end

  # POST /links
  # POST /links.json
  def create
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    url_newlink = link_params[:url]
    if url_newlink != '' && Link.exists?(url: url_newlink)
      redirect_to ("/links/"+(Link.find_by(url: url_newlink).id).to_s)
      return
    end
    @link = Link.new(link_params)
    @link.user_id = current_user.id

    respond_to do |format|
      if @link.save
        format.html { redirect_to "/links/new_index", notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_back fallback_location: root_path
  end

  def downvote
    unless is_logged_in?
      redirect_to "/auth/google_oauth2"
      return
    end
    @link = Link.find(params[:id])
    @link.unvote_by current_user
    redirect_back fallback_location: root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url, :text)
    end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_with(model: link, local: true) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :url %><br>
    <%= form.text_field :url, class: "form-control" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :text %><br>
    <%= form.text_area :text, class: "form-control" %>
  </div>
  <br>
  
  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/links/ask.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title, link %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by 
      <%= link_to link.user.name, "/users/"+link.user.id.to_s %></small>
    </h2>

    <!-- Vote implementation -->
    <div class="btn-group">
      <% if link.user != current_user -%>
        <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down">
          Unvote
        <% end %>
      <% end %>
    </div>

  </div>
<% end %>    

app/views/links/edit.html.erb
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path , class: "btn btn-default"%>

app/views/links/index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title, link %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by 
      <%= link_to link.user.name, "/users/"+link.user.id.to_s %></small>
    </h2>

    <!-- Vote implementation -->
    <div class="btn-group">
      <%unless link.url == '' %>
        <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
      <% end %>
      <% if link.user != current_user -%>
        <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down">
          Unvote
        <% end %>
      <% end %>
    </div>

  </div>
<% end %>    

app/views/links/my_links.html.erb
<p id="notice"><%= notice %></p>

<h1>My links</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.id %></td>
        <td><%= link.title %></td>
        <div class="btn-group">
        <td><%= link_to 'Show', "/links/"+link.id.to_s , class: "btn btn-default"%></td>
        <td><%= link_to 'Edit', edit_link_path(link), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/links/new.html.erb
<h1>New Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Back', links_path , class: "btn btn-default"%>

app/views/links/new_index.html.erb
<% @links.each do |link| %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title, link %><br>
      <small class="author">Submitted <%= time_ago_in_words(link.created_at) %> by 
      <%= link_to link.user.name, "/users/"+link.user.id.to_s %></small>
    </h2>

    <!-- Vote implementation -->
    <div class="btn-group">
      <%unless link.url == '' %>
        <a class="btn btn-default btn-sm" href="<%= link.url %>">Visit Link</a>
      <% end %>
      <% if link.user != current_user -%>
        <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-up"></span>
          Upvote
          <%= link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm" do %>
          <span class="glyphicon glyphicon-chevron-down">
          Unvote
        <% end %>
      <% end %>
    </div>

  </div>
<% end %>    

app/views/links/show.html.erb
<div class="page-header">
  <h1><a href="<%= @link.url %>"><%= @link.title %></a><br> <small>Submitted by <%= link_to @link.user.name, "/users/"+@link.user.id.to_s %></small></h1>
</div>

<%unless @link.url == '' %>
  <div class="btn-group">
    <%= link_to 'Visit URL', @link.url, class: "btn btn-primary" %>
  </div>
<% end %>

<% if @link.user == current_user -%>
    <div class="btn-group">
      <%= link_to 'Edit', edit_link_path(@link), class: "btn btn-default" %>
      <%= link_to 'Destroy', @link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
    </div>
  <% else %>
    <div class="btn-group pull-right">
      <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= @link.get_upvotes.size %>
      <% end %>
      <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
        Unvote
      <% end %>
    </div>
<% end %>

<h3 class="comments_title">
  <%= @link.comments.count %> Comments
</h3>

<div id="comments">
  <%= render :partial => @link.comments %>
</div>
<%= simple_form_for [@link, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
    <%= hidden_field_tag "link_id", "#{@link.id}" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>

app/views/links/voted_links.html.erb
<p id="notice"><%= notice %></p>

<h1>Voted links</h1>

<table>
  <thead>
    <tr>
      <th>Link</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.id %></td>
        <td><%= link.title %></td>
        <div class="btn-group">
        <td><%= link_to 'Show', "/links/"+link.id.to_s , class: "btn btn-default"%></td>
        <td><%= link_to 'Edit', edit_link_path(link), class: "btn btn-default" %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>