config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  get 'links/new_index', to: 'links#new_index'
  get "links/ask" => "links#ask"
  get 'comments/threads' => 'comments#threads'
  get 'comments/voted_comments' => 'comments#voted_comments'
  get 'links/my_links' => 'links#my_links'
  get 'links/voted_links' => 'links#voted_links'

  resources :sessions, only: [:create, :destroy]

  resources :comments do
    member do
      put "like",    to: "comments#upvote"
      put "dislike", to: "comments#downvote"
      post "reply", to: "comments#doReply"
    end
    resources :comments
  end

  resources :links do
    member do
      put "like",    to: "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  resources :users
  root to: "links#index"

  namespace 'api' do

    #LINKS
    root "links#index"
    get "/submissions" => "links#index"
    get "/ask" => "links#ask"
    get "/newest" => "links#new_index"
    get "/submissions/:id" => "links#show"
    post "/submissions" => "links#submit"
    delete "/submissions/:id" => "links#delete"

    #COMMENTS
    get "/threads" => "comments#threads"
    delete "/comments/:id" => "comments#delete"
    get "/comments/:id" => "comments#show"
    post "/comments" => "comments#new"

    # USERS
    get "/users/:id" => "users#profile"
    put "/users/:id" => "users#update_user"
    post "/vote_submission" => "users#vote_submission"
    post "/vote_comment" => "users#vote_comment"

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fib News</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Fib News", root_path %></div>
        <nav class="collapse navbar-collapse navbar-ex1-collapse">
					<ul class="nav navbar-nav navbar-default">
						<li><%= link_to 'New', "/links/new_index" %></li>
						<li><%= link_to 'Ask', "/links/ask" %></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<% if current_user -%>
							<li><%= link_to 'Threads', "/comments/threads" %></li>
							<li><%= link_to 'Submit link', new_link_path %></li>
							<li><%= link_to 'Account', "/users/"+current_user.id.to_s %></li>
							<li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
						<% else -%>
							<ul class="nav navbar-nav navbar-right">
							<li><%= link_to "Sign in", "/auth/google_oauth2", id: "sign_in" %></li>
							</ul>
						<% end -%>
					</ul>
        </nav>
      </div>
    </div>
  </header>

	<div id="main_content" class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>

			<div id="content" class="col-md-9 center-block">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
</html>